Homework 3 Task 1.Totjmyanin
iraedeus/spbu_sem1_DT pull request #16
Opened 2023-10-04 15:27 UTC by iraedeus

Added documentation to functions

2023-10-12 16:34 UTC, toadharvard commented
Кринжовые названия файлов и коммитов. Ты читал, что я скидывал?

2023-10-12 16:52 UTC, toadharvard requested changes

2023-10-12 16:52 UTC, toadharvard commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +    global user_function
Никаких глобальных переменных

2023-10-12 16:52 UTC, toadharvard commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +        return function()
Ты вместо карирования функции вызываешь ее, получится, что карирование == вызов, что не соответствует таске

2023-10-12 17:03 UTC, toadharvard commented
Функции после применения карирования теряют метаинформацию, подумай как интегрировать @functools.wraps

2023-10-16 19:22 UTC, toadharvard requested changes

2023-10-16 19:22 UTC, toadharvard commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +user_function = None
Тут осталось)

2023-10-16 19:22 UTC, toadharvard commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +        curry.__name__ = function.__name__
Хотя ты все равно не всю метаинформацию сохранил(документация исчезнет), но хоть что-то, спасибо что глянул

2023-10-16 19:22 UTC, toadharvard commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +def curry_explicit(function, arity):
А если передали arity < 0?

2023-10-16 19:22 UTC, toadharvard commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +            raise Exception("Wrong arity")
Слишком общее исключение, лучше бы ValueError и более подробное описание того, как исправить арити

2023-10-16 19:22 UTC, toadharvard commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +            raise Exception("Wrong arity")
Но это лучше чем ничего

2023-10-17 09:35 UTC, SpirinEgor requested changes

2023-10-17 09:35 UTC, SpirinEgor commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +        curry.__doc__ = function.__doc__
Круто, что задумался об этом. Но в питоне уже за тебя все придумали)
[`update_wrapper`](https://docs.python.org/3/library/functools.html#functools.update_wrapper)

2023-10-17 09:35 UTC, SpirinEgor commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +        nonlocal function
Кажется тут вполне можно обойтись и без захвата внешней переменной

2023-10-17 09:35 UTC, SpirinEgor commented on src/homework/homework-3/Homework 3 Task 1.Totjmyanin.py
> +    get_args.__doc__ = function.__doc__
Тот же комментарий про update_wrapper

2023-10-19 13:32 UTC, SpirinEgor approved these changes

2023-10-19 13:34 UTC, toadharvard approved these changes

2023-10-19 13:34 UTC, merged